// language.js (v4.0 최종 버전)

const languageData = {
    ko: {
        app_title: "NoaDot - 이미지/텍스트 변환기",
        app_header: "🎨 NoaDot v4.0",
        section_mode: "1. 모드 선택",
        mode_image: "🖼️ 이미지",
        mode_text: "✏️ 텍스트",
        info_original_size: "원본 크기",
        info_converted_size: "변환 크기",
        info_generated_size: "생성 크기",
        section_resize: "2. 크기 조절",
        resize_mode: "조절 방식",
        resize_pixel: "픽셀 단위",
        resize_ratio: "비율 단위",
        resize_scale_ratio: "축소 비율",
        resize_pixel_amount: "픽셀 축소량",
        resize_width: "너비",
        resize_height: "높이",
        section_text_style: "2. 텍스트 스타일",
        text_upload_font: "폰트+",
        text_font_size: "글자 크기",
        text_letter_spacing: "자간",
        text_padding: "여백",
        text_stroke_width: "테두리 두께",
        text_color: "글자색",
        text_stroke_color: "테두리색",
        text_bg_color: "배경색",
        text_bold: "굵게",
        text_italic: "기울임",
        section_options: "3. 변환 옵션",
        option_saturation: "채도",
        option_brightness: "밝기",
        option_contrast: "대비",
        option_dithering: "디더링",
        dithering_floyd: "플로이드-스타인버그",
        dithering_sierra: "시에라-2",
        dithering_atkinson: "애킨슨",
        dithering_none: "사용 안함",
        option_dithering_strength: "디더링 강도",
        
        // [신규] 패턴 적용 관련
        option_apply_pattern: "패턴 적용 (베타)",
        pattern_type: "패턴 종류",
        pattern_size: "패턴 크기",
        pattern_crosshatch: "격자",
        pattern_vertical: "수직선",
        pattern_checkerboard: "체커보드",
        pattern_diagonal_right: "대각선 (↙)",
        pattern_diagonal_left: "대각선 (↘)",
        pattern_brick: "벽돌",
        
        option_hq_mode: "고품질 색상 계산 (느림)",
        option_cartoon_filter: "만화 스타일 필터",
        cartoon_color_level: "색상 레벨",
        cartoon_show_outline: "외곽선 표시",
        section_palette: "4. 팔레트 선택",
        palette_geopixels_default: "GeoPixels 기본 팔레트",
        palette_use_wplace: "Wplace 팔레트 사용하기",
        palette_use_wplace_in_geo: "GeoPixels 모드에서 Wplace 팔레트 함께 사용",
        palette_wplace_free: "Wplace 무료",
        palette_wplace_paid: "Wplace 유료",
        palette_user: "사용자 팔레트",
        section_color_extract: "색상 추출 추천",
        extract_highlight_sensitivity: "하이라이트 탐지 감도",
        extract_mode_high_usage: "고비율 색상",
        extract_mode_highlight: "하이라이트",
        palette_added_colors: "추가한 색상",
        palette_or: "또는",
        btn_add: "추가",
        btn_reset_added_colors: "추가한 색상 전체 초기화",
        section_palette_io: "팔레트 가져오기/내보내기",
        info_palette_io: "현재 '추가한 색상' 목록을 파일로 저장하거나, 파일에서 불러옵니다.",
        btn_export_palette: "파일로 내보내기",
        btn_import_palette: "파일에서 불러오기",
        btn_download: "다운로드",
        placeholder_image_upload: "창 클릭 혹은 이미지를 화면으로 드래그",
        placeholder_text_editor: "여기에 텍스트를 입력하세요...",
        placeholder_recommend: "이미지를 업로드하면<br>추천 색상이 표시됩니다.",
        placeholder_add_color: "아래에서 직접 색상을 추가하세요.",
        placeholder_hex: "HEX 코드 입력 (예: #FF595E)",
        placeholder_text_preview: "왼쪽에서 텍스트를 입력하면 여기에 미리보기가 표시됩니다.",
        
        // 툴팁
        tooltip_dithering: "제한된 색상으로 이미지의 색을 표현할 때, 점을 찍는 방식으로 색상 간의 경계를 부드럽게 만들어 계단 현상을 줄여주는 기법입니다. 이미지의 디테일을 향상시킵니다.",
        tooltip_pattern: "이미지의 명암과 패턴 지도를 비교하여, 팔레트 내의 가장 가까운 두 색상으로 픽셀을 다시 그립니다. 일반 디더링과 함께 사용하면 더 복합적인 질감을 만들 수 있습니다. (만화 스타일 필터와는 함께 사용할 수 없습니다.)",
        tooltip_hq_mode: "사람의 시각에 더 가깝게 색상 차이를 계산하는 Oklab/CIEDE2000 방식을 사용합니다. 색상의 정확도가 크게 향상되지만, 변환 속도가 느려질 수 있습니다.",
        tooltip_cartoon_filter: "이미지를 단순한 색상 면으로 재구성하여 만화처럼 만듭니다. 이 기능은 점으로 디테일을 표현하는 '디더링'이나 '패턴'과 정반대의 원리로 동작하므로, 함께 사용 시 다른 효과가 무시될 수 있습니다.",
        tooltip_highlight_sensitivity: "색상 추천 시, 이미지의 경계선이나 복잡한 패턴 주변의 '하이라이트 색상'을 얼마나 민감하게 찾아낼지 조절합니다. 값이 높을수록 더 미세한 하이라이트도 탐지합니다.",
        tooltip_center_zoom: "화면 중앙 및 확대/축소 초기화",
        tooltip_bold: "굵게",
        tooltip_italic: "기울임",

        // 알림 메시지
        alert_no_color_to_export: "내보낼 색상이 없습니다.",
        alert_no_color_to_reset: "초기화할 색상이 없습니다.",
        confirm_reset_added_colors: "정말로 추가한 모든 색상을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        confirm_load_palette_from_png: "이미지에서 '추가한 색상' 목록을 발견했습니다. 현재 목록을 덮어쓰고 불러오시겠습니까?",
        alert_png_metadata_info: "해당 이미지는 NoaDot을 통해 변환된 기록이 있습니다.",
        confirm_mode_switch_to_text: "모드를 전환하시면 업로드한 이미지 내용은 초기화됩니다. 계속하시겠습니까?",
        confirm_mode_switch_to_image: "모드를 전환하시면 작성하신 텍스트 내용은 초기화됩니다. 계속하시겠습니까?",
        alert_already_added: "이미 추가된 색상입니다.",
        placeholder_no_recommendations: "선택된 모드에 맞는<br>추천 색상이 없습니다.",
        alert_some_colors_failed: "일부 색상을 추가하지 못했습니다. (중복 또는 유효하지 않은 형식)",
        placeholder_no_recommendations: "선택된 모드에 맞는<br>추천 색상이 없습니다.",

        option_apply_gradient: "투명도 그라데이션 적용",
        gradient_angle: "각도",
        gradient_strength: "강도",
        tooltip_gradient: "이미지에 선형 그라데이션으로 점차 투명해지는 디더링 효과를 적용합니다. '각도'로 방향을, '강도'로 전체적인 투명도를 조절할 수 있습니다.",
        extract_mode_smh : "명암 대표색",
        placeholder_no_new_recommendations: "현재 모드에 대한 새로운 추천 색상이 없거나, 모든 색상이 이미 추가되었습니다.",
    },
    en: {
        app_title: "NoaDot - Image/Text Converter",
        app_header: "🎨 NoaDot v4.0",
        section_mode: "1. Select Mode",
        mode_image: "🖼️ Image",
        mode_text: "✏️ Text",
        info_original_size: "Original Size",
        info_converted_size: "Converted Size",
        info_generated_size: "Generated Size",
        section_resize: "2. Resize",
        resize_mode: "Method",
        resize_pixel: "By Pixel",
        resize_ratio: "By Ratio",
        resize_scale_ratio: "Scale Ratio",
        resize_pixel_amount: "Pixel Reduction",
        resize_width: "Width",
        resize_height: "Height",
        section_text_style: "2. Text Style",
        text_upload_font: "Font+",
        text_font_size: "Font Size",
        text_letter_spacing: "Letter Spacing",
        text_padding: "Padding",
        text_stroke_width: "Stroke Width",
        text_color: "Text Color",
        text_stroke_color: "Stroke Color",
        text_bg_color: "BG Color",
        text_bold: "Bold",
        text_italic: "Italic",
        section_options: "3. Conversion Options",
        option_saturation: "Saturation",
        option_brightness: "Brightness",
        option_contrast: "Contrast",
        option_dithering: "Dithering",
        dithering_floyd: "Floyd-Steinberg",
        dithering_sierra: "Sierra-2",
        dithering_atkinson: "Atkinson",
        dithering_none: "None",
        option_dithering_strength: "Dithering Strength",

        // [New] Pattern related
        option_apply_pattern: "Apply Pattern (Beta)",
        pattern_type: "Pattern Type",
        pattern_size: "Pattern Size",
        pattern_crosshatch: "Crosshatch",
        pattern_vertical: "Vertical Lines",
        pattern_checkerboard: "Checkerboard",
        pattern_diagonal_right: "Diagonal (↙)",
        pattern_diagonal_left: "Diagonal (↘)",
        pattern_brick: "Brick",

        option_hq_mode: "High Quality Color Calc (Slow)",
        option_cartoon_filter: "Cartoon Style Filter",
        cartoon_color_level: "Color Levels",
        cartoon_show_outline: "Show Outline",
        section_palette: "4. Select Palette",
        palette_geopixels_default: "GeoPixels Default Palette",
        palette_use_wplace: "Use Wplace Palette",
        palette_use_wplace_in_geo: "Use Wplace palette in GeoPixels mode",
        palette_wplace_free: "Wplace Free",
        palette_wplace_paid: "Wplace Paid",
        palette_user: "User Palette",
        section_color_extract: "Color Extraction",
        extract_highlight_sensitivity: "Highlight Detection Sensitivity",
        extract_mode_high_usage: "High Usage",
        extract_mode_highlight: "Highlights",
        palette_added_colors: "Added Colors",
        palette_or: "or",
        btn_add: "Add",
        btn_reset_added_colors: "Reset All Added Colors",
        section_palette_io: "Import / Export Palette",
        info_palette_io: "Export the current 'Added Colors' list to a file, or import from a file.",
        btn_export_palette: "Export to File",
        btn_import_palette: "Import from File",
        btn_download: "Download",
        placeholder_image_upload: "Click or drag & drop an image here",
        placeholder_text_editor: "Enter text here...",
        placeholder_recommend: "Upload an image to see<br>recommended colors.",
        placeholder_add_color: "Add colors from the inputs below.",
        placeholder_hex: "Enter HEX code (e.g., #FF595E)",
        placeholder_text_preview: "Enter text on the left to see a preview here.",

        // Tooltips
        tooltip_dithering: "A technique that uses dots to simulate shades and reduce color banding when using a limited color palette. It improves the detail of the image.",
        tooltip_pattern: "Compares the image's brightness with a pattern map to redraw pixels using the two closest colors from the palette. Can be combined with standard dithering for more complex textures. (Cannot be used with Cartoon Filter.)",
        tooltip_hq_mode: "Uses Oklab/CIEDE2000 for more perceptually accurate color difference calculations. Greatly improves color accuracy but may slow down conversion.",
        tooltip_cartoon_filter: "Reconstructs the image with flat color areas for a cartoon-like feel. As this works opposite to dithering or patterns, other effects may be ignored.",
        tooltip_highlight_sensitivity: "Controls how sensitively 'highlight colors' are detected around edges and complex patterns for color recommendation. Higher values detect more subtle highlights.",
        tooltip_center_zoom: "Center view and reset zoom",
        tooltip_bold: "Bold",
        tooltip_italic: "Italic",

        // Alerts
        alert_no_color_to_export: "There are no colors to export.",
        alert_no_color_to_reset: "There are no colors to reset.",
        confirm_reset_added_colors: "Are you sure you want to delete all added colors? This action cannot be undone.",
        confirm_load_palette_from_png: "An 'Added Colors' list was found in the image. Overwrite the current list and load it?",
        alert_png_metadata_info: "This image contains a record of being converted by NoaDot.",
        confirm_mode_switch_to_text: "Switching modes will reset the uploaded image. Continue?",
        confirm_mode_switch_to_image: "Switching modes will reset your text. Continue?",
        alert_already_added: "This color has already been added.",
        placeholder_no_recommendations: "No recommended colors found<br>for the selected mode.",
        alert_some_colors_failed: "Failed to add some colors (duplicates or invalid format).",
        placeholder_no_recommendations: "No recommended colors found<br>for the selected mode.",
        
        option_apply_gradient: "Apply Transparency Gradient",
        gradient_angle: "Angle",
        gradient_strength: "Strength",
        tooltip_gradient: "Applies a dithered transparency effect in a linear gradient. 'Angle' controls the direction, and 'Strength' controls the overall transparency.",
         extract_mode_smh : "Tonal Range",
        placeholder_no_new_recommendations: "No new recommendations for this mode, or all have been added.",
    }
};